### ISSUE TITLE
Some Positioning

### ISSUE THREAD

**Issue by hairarrow** [nullism/clickingbad#143]
Consider adding to game.css

``` css
.left_width {
    position: fixed;
}
```

and changing the other column to 

``` css
float: right;
```

I'm currently doing this every time I use this, just for shigs.
